### ISSUE TITLE
Running Recording After Installation

### ISSUE THREAD

**Issue by ckhdd** [hcfman/sbts-aru#2]
Hello Mr. Hendrikse
We are a group of undergrade working on a sound tracking device, and your project caught our eye at the first time. (thanks and credit to you). We successfully set up the installation and the hardware set, but we are struggling with the execution of recording and localizing. We wonder if, by any chance, you can provide more details running the jackd and sbts-aru after installation.

Thank you very much!

**Comment by hcfman** [comment]
Okay, can you indicate how far you got to? The startup script in /etc/rc.local will not start the recording unless there is a GPS correctly attached and it has satellite lock. The GPS has to have the PPS signal attached as in the README.

If you have the GPS attached, then you can check the progress of acquiring the satellites by running gpsmon. There should be a place where it says how many satellites are locked, it needs 5. On the neo series, I think that's next to a keyword PRN on adafruit I think it next to SATS.

If it has satellite lock, it will not start recording until the system clock has an accuracy measured in the nano seconds. You can check this with the chronyc sources command. If the PPS is used as a source it has a start in the first column. If it has that, then it's usually sub-microsecond accuracy without a minute. If not, read about this in the README.

Localization first requires you to detail the date and time in the following form:

2023-10-01_22-41-19.065072

This is the form output by the gps_event_time.py which you use to get this time. The usage of that program is to provide in argument #1 the start time of the first, this is copied from the date/time from the beginning part of the filename itself. The second argument is the offset in seconds and microseconds within the file to the event start. This is easiest obtained with raven lite, but audacity can be used as well. The last parameter is always 2048 unless you changed the buffer size of jackd in /etc/rc.local.

If you have the dates and times in that form for at least #3 recorders, then you run localize_event.sh (Or .py if you path is correct) with as input lines in the following form:

51.01415,5.813725 2023-09-17_15-49-48.523601
51.015365,5.81165 2023-09-17_15-49-48.822030
51.016368332,5.814084879 2023-09-17_15-49-48.715324
51.015221667,5.815915 2023-09-17_15-49-48.545999

The co-ordinates need to be separated by a comma followed by a space.

And the result and maps co-ordinates will be output.

I'd also be happy to provide you some training over a google meet meeting if you like? Just reach out to me over linkedin and we can schedule something. That would be the quickest way to get you started right now.

https://www.linkedin.com/in/kim-hendrikse-2427643/

I also have intentions to write a series of articles on medium.com or the like but at the moment I have some other commitments to add wolf and bear detection to my computer vision security project (https://github.com/hcfman/sbts-install) I have to attend to for a while that were neglected when I got side tracked on this localization project :)

**Comment by hcfman** [comment]
Oh, and something I haven't documented yet. You cannot use a file unless it has been closed. If it's closed it will have both a start and an end date in the file name. If it's open, and you have recorded something and can't wait, then you can send a HUP signal to the recorder process and it will close the current file and start a new one. This can be done with the following command:

pkill -HUP -f sbts-aru

**Comment by hcfman** [comment]
And note also, that the opensoundscape library is only installed on Pi's with 2GB or more of memory.

And there are a couple undocumented helper programs.

eventtime.py to add seconds to a date/time string as in:

$ eventtime.py 2023-11-26_00-44-35.767448 10.45343
2023-11-26_00-44-46.220878

And time_diffs.py which are helpful to find offsets into files as in:

$ time_diffs.py 
2023-11-26_00-44-35.767448
2023-11-26_00-44-35.836343            

0.000000
0.068895

Frequently, once I have the TDOA from one microphone, I use the time_diffs.py program with the start time of another file and the determined event date/time as the inputs and it gives me the offset in the new file. This is helpful if localizing over a really long distance where the event can in principle be heard, but it is of such low level you need to know where to look. Often, you can just see a slight jump on the spectram and that's enough to determine that that was the same event (In the case of explosions from fireworks for example). In this manner I'm able to localize fireworks from mics 5km away.

**Comment by hcfman** [comment]
Scheduled a zoom meeting to help with this
